import type { Metadata } from 'next';
import Header from './components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header></Header>
      <main className="mx-auto max-w-1920 px-[150px]">{children}</main>
    </>
  );
}
