import { Metadata } from 'next';

import Questions from './questions';

export const metadata: Metadata = {
  title: 'Frequently Asked Questions',
  description: 'Generated by create next app',
  openGraph: {
    title: 'This is lion',
    description: 'cool lion image',
    images: [
      'https://www.krugerpark.co.za/images/black-maned-lion-shem-compion-786x500.jpg',
    ],
    url: `https://dajavshne-fe-xi.vercel.app/faq`,
  },
};

const FaqPage = () => {
  return (
    <div className="px-4 md:px-6 2xl:px-desktop">
      <h1 className="text-2xl font-bold lg:text-[40px] lg:leading-[52px]">
        F.A.Q
      </h1>
      <p className="mt-4 text-sm text-black/30 lg:text-base">
        Have questions ? We’re here to help.
      </p>
      <Questions />
    </div>
  );
};

export default FaqPage;
