import { Metadata } from 'next';

import Questions from './questions';

export const metadata: Metadata = {
  title: 'Frequently Asked Questions',
  description: 'Generated by create next app',
};

const FaqPage = () => {
  return (
    <div className="px-4 md:px-6 2xl:px-desktop">
      <h1 className="text-2xl font-bold lg:text-[40px] lg:leading-[52px]">
        F.A.Q
      </h1>
      <p className="mt-4 text-sm text-black/30 lg:text-base">
        Have questions ? We’re here to help.
      </p>
      <Questions />
    </div>
  );
};

export default FaqPage;
