import type { Metadata } from 'next';
import Link from 'next/link';
import { ReactNode } from 'react';

import LogoIcon from '@/icons/LogoIcon';

import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function UserLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <main>
      <div className="flex min-h-screen w-screen">
        <div className="bg-car-tyre hidden w-3/5 bg-cover bg-center lg:block">
          <div className="flex size-full items-center justify-center bg-black/30">
            <Link href="/" className="h-auto w-2/5">
              <LogoIcon className="h-auto w-full [&>path]:fill-beige" />
            </Link>
          </div>
        </div>
        <div className="w-full px-4 lg:w-2/5 lg:px-14 2xl:px-desktop">
          {children}
        </div>
      </div>
    </main>
  );
}
